name: UnifiedMetrics
main: dev.cubxity.plugins.metrics.bungee.bootstrap.UnifiedMetricsBungeeBootstrap
description: "Fully-featured metrics plugin for Minecraft servers"
author: Cubxity
version: ${version}